"""campusshare_initial_schema

Revision ID: 6a4026c5d35e
Revises: 
Create Date: 2026-10-01 16:46:45.917032
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a4026c5d35e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('year >= 1', name='ck_student_year_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('preferred_duration_days', sa.Integer(), nullable=False),
    sa.Column('pickup_location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preferred_duration_days >= 1', name='ck_item_duration_positive'),
    sa.ForeignKeyConstraint(['owner_student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_category'), 'item', ['category'], unique=False)
    op.create_index('ix_item_category_available', 'item', ['category', 'available'], unique=False)
    op.create_index(op.f('ix_item_owner_student_id'), 'item', ['owner_student_id'], unique=False)
    op.create_table('borrow_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('borrower_student_id', sa.Integer(), nullable=False),
    sa.Column('lender_student_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'active', 'returned')", name='ck_borrow_request_status'),
    sa.CheckConstraint('actual_return_date IS NULL OR actual_return_date >= start_date', name='ck_borrow_request_actual_return_date'),
    sa.CheckConstraint('borrower_student_id <> lender_student_id', name='ck_borrow_request_distinct_students'),
    sa.CheckConstraint('expected_return_date >= start_date', name='ck_borrow_request_dates'),
    sa.ForeignKeyConstraint(['borrower_student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lender_student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_borrow_request_borrower_status', 'borrow_request', ['borrower_student_id', 'status'], unique=False)
    op.create_index(op.f('ix_borrow_request_borrower_student_id'), 'borrow_request', ['borrower_student_id'], unique=False)
    op.create_index(op.f('ix_borrow_request_item_id'), 'borrow_request', ['item_id'], unique=False)
    op.create_index('ix_borrow_request_lender_status', 'borrow_request', ['lender_student_id', 'status'], unique=False)
    op.create_index(op.f('ix_borrow_request_lender_student_id'), 'borrow_request', ['lender_student_id'], unique=False)
    op.create_index('ix_borrow_request_status_due', 'borrow_request', ['status', 'expected_return_date'], unique=False)
    op.create_table('saved_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'item_id', name='uq_saved_item_student_item')
    )
    op.create_index(op.f('ix_saved_item_item_id'), 'saved_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_saved_item_student_id'), 'saved_item', ['student_id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('rater_student_id', sa.Integer(), nullable=False),
    sa.Column('rated_student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rater_student_id <> rated_student_id', name='ck_rating_distinct_students'),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='ck_rating_score_range'),
    sa.ForeignKeyConstraint(['rated_student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rater_student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['borrow_request.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'rater_student_id', name='uq_rating_request_rater')
    )
    op.create_index(op.f('ix_rating_rated_student_id'), 'rating', ['rated_student_id'], unique=False)
    op.create_index(op.f('ix_rating_rater_student_id'), 'rating', ['rater_student_id'], unique=False)
    op.create_index(op.f('ix_rating_request_id'), 'rating', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_request_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_rater_student_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_rated_student_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_saved_item_student_id'), table_name='saved_item')
    op.drop_index(op.f('ix_saved_item_item_id'), table_name='saved_item')
    op.drop_table('saved_item')
    op.drop_index('ix_borrow_request_status_due', table_name='borrow_request')
    op.drop_index(op.f('ix_borrow_request_lender_student_id'), table_name='borrow_request')
    op.drop_index('ix_borrow_request_lender_status', table_name='borrow_request')
    op.drop_index(op.f('ix_borrow_request_item_id'), table_name='borrow_request')
    op.drop_index(op.f('ix_borrow_request_borrower_student_id'), table_name='borrow_request')
    op.drop_index('ix_borrow_request_borrower_status', table_name='borrow_request')
    op.drop_table('borrow_request')
    op.drop_index(op.f('ix_item_owner_student_id'), table_name='item')
    op.drop_index('ix_item_category_available', table_name='item')
    op.drop_index(op.f('ix_item_category'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
